Imports System.Speech
Imports System.Speech.Synthesis
Public Class voicedemo
    Dim p As New SpeechSynthesizer()
    ' Dim Speech As Object = CreateObject("SAPI.SpVoice")
    Private Sub voicedemo_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        p.SpeakAsync("Number 1 Page is the startup window of the software.")
        p.SpeakAsync("To proceed to new page click Enter button to proceed")

        p.SpeakAsync("Number Second Page is the Login Page of software.")
        p.SpeakAsync("For Entering to the software you need to enter your username and password generated by the software.")
        p.SpeakAsync("After entering the username and password click on login button.")

        p.SpeakAsync("Here it will open the Third Number Page of the Main Menu Window into the software from where yout are able to carry out various tasks like inward or outward enteries and many more.")
        p.SpeakAsync("First button that is customer in the left corner will take you to the customer entry page")
        p.SpeakAsync("Second Button that is inward entry will take you to the inward entry page where you can have multiple inward entries of a customer.")
        p.SpeakAsync("Third Button that is outward entry will take you to the outward entry page where you can discard the customer goods from the storage ")
        p.SpeakAsync("Fourth button that is Billmaster  will  take you to the billMaster where you are able to make bills of customers after discarding their goods after outward entries.")
        p.SpeakAsync("Fifth button that is search button will take to for analyzing record of the customer .")
        p.SpeakAsync("sixth button that is About will display the information about the developers")
        p.SpeakAsync("This is all about the software,Might it helped you")

    End Sub

   
   
    Private Sub Button1_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        Dim a As New Menu
        p.SpeakAsyncCancelAll()
        a.Show()
        Me.Hide()
    End Sub

    Private Sub Panel3_Paint(ByVal sender As System.Object, ByVal e As System.Windows.Forms.PaintEventArgs) Handles Panel3.Paint

    End Sub
End Class